// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: about.sql

package db

import (
	"context"
)

const getSiteSetting = `-- name: GetSiteSetting :one
SELECT key, value, updated_at
FROM site_settings
WHERE key = $1
`

func (q *Queries) GetSiteSetting(ctx context.Context, key string) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSiteSetting, key)
	var i SiteSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const upsertSiteSetting = `-- name: UpsertSiteSetting :one
INSERT INTO site_settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET
  value = EXCLUDED.value,
  updated_at = now()
RETURNING key, value, updated_at
`

type UpsertSiteSettingParams struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

func (q *Queries) UpsertSiteSetting(ctx context.Context, arg UpsertSiteSettingParams) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, upsertSiteSetting, arg.Key, arg.Value)
	var i SiteSetting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
