// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAdminProjectBySlug = `-- name: GetAdminProjectBySlug :one
SELECT
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
FROM projects
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAdminProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getAdminProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Client,
		&i.Role,
		&i.Summary,
		&i.Body,
		&i.ThumbnailUrl,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByEmail,
		&i.CreatedByDisplayName,
		&i.UpdatedByEmail,
		&i.UpdatedByDisplayName,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
`

type InsertProjectParams struct {
	Slug                 string             `json:"slug"`
	Title                string             `json:"title"`
	Client               string             `json:"client"`
	Role                 string             `json:"role"`
	Summary              string             `json:"summary"`
	Body                 []byte             `json:"body"`
	ThumbnailUrl         string             `json:"thumbnail_url"`
	SortOrder            int32              `json:"sort_order"`
	Status               string             `json:"status"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	CreatedByEmail       string             `json:"created_by_email"`
	CreatedByDisplayName string             `json:"created_by_display_name"`
	UpdatedByEmail       string             `json:"updated_by_email"`
	UpdatedByDisplayName string             `json:"updated_by_display_name"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.Slug,
		arg.Title,
		arg.Client,
		arg.Role,
		arg.Summary,
		arg.Body,
		arg.ThumbnailUrl,
		arg.SortOrder,
		arg.Status,
		arg.PublishedAt,
		arg.CreatedByEmail,
		arg.CreatedByDisplayName,
		arg.UpdatedByEmail,
		arg.UpdatedByDisplayName,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Client,
		&i.Role,
		&i.Summary,
		&i.Body,
		&i.ThumbnailUrl,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByEmail,
		&i.CreatedByDisplayName,
		&i.UpdatedByEmail,
		&i.UpdatedByDisplayName,
	)
	return i, err
}

const listAdminProjects = `-- name: ListAdminProjects :many
SELECT
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
FROM projects
WHERE deleted_at IS NULL
ORDER BY sort_order ASC
`

func (q *Queries) ListAdminProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listAdminProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Client,
			&i.Role,
			&i.Summary,
			&i.Body,
			&i.ThumbnailUrl,
			&i.SortOrder,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedByEmail,
			&i.CreatedByDisplayName,
			&i.UpdatedByEmail,
			&i.UpdatedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProjectBySlug = `-- name: SoftDeleteProjectBySlug :one
UPDATE projects SET
  deleted_at = now(),
  updated_by_email = $2,
  updated_by_display_name = $3,
  updated_at = now()
WHERE slug = $1
  AND deleted_at IS NULL
RETURNING
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
`

type SoftDeleteProjectBySlugParams struct {
	Slug                 string `json:"slug"`
	UpdatedByEmail       string `json:"updated_by_email"`
	UpdatedByDisplayName string `json:"updated_by_display_name"`
}

func (q *Queries) SoftDeleteProjectBySlug(ctx context.Context, arg SoftDeleteProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, softDeleteProjectBySlug, arg.Slug, arg.UpdatedByEmail, arg.UpdatedByDisplayName)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Client,
		&i.Role,
		&i.Summary,
		&i.Body,
		&i.ThumbnailUrl,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByEmail,
		&i.CreatedByDisplayName,
		&i.UpdatedByEmail,
		&i.UpdatedByDisplayName,
	)
	return i, err
}

const updateProjectBySlug = `-- name: UpdateProjectBySlug :one
UPDATE projects SET
  slug = $1,
  title = $2,
  client = $3,
  role = $4,
  summary = $5,
  body = $6,
  thumbnail_url = $7,
  sort_order = $8,
  status = $9,
  published_at = $10,
  updated_by_email = $11,
  updated_by_display_name = $12,
  updated_at = now()
WHERE slug = $13
  AND deleted_at IS NULL
RETURNING
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
`

type UpdateProjectBySlugParams struct {
	NewSlug              string             `json:"new_slug"`
	Title                string             `json:"title"`
	Client               string             `json:"client"`
	Role                 string             `json:"role"`
	Summary              string             `json:"summary"`
	Body                 []byte             `json:"body"`
	ThumbnailUrl         string             `json:"thumbnail_url"`
	SortOrder            int32              `json:"sort_order"`
	Status               string             `json:"status"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	UpdatedByEmail       string             `json:"updated_by_email"`
	UpdatedByDisplayName string             `json:"updated_by_display_name"`
	Slug                 string             `json:"slug"`
}

func (q *Queries) UpdateProjectBySlug(ctx context.Context, arg UpdateProjectBySlugParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectBySlug,
		arg.NewSlug,
		arg.Title,
		arg.Client,
		arg.Role,
		arg.Summary,
		arg.Body,
		arg.ThumbnailUrl,
		arg.SortOrder,
		arg.Status,
		arg.PublishedAt,
		arg.UpdatedByEmail,
		arg.UpdatedByDisplayName,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Client,
		&i.Role,
		&i.Summary,
		&i.Body,
		&i.ThumbnailUrl,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByEmail,
		&i.CreatedByDisplayName,
		&i.UpdatedByEmail,
		&i.UpdatedByDisplayName,
	)
	return i, err
}

const updateProjectSortOrder = `-- name: UpdateProjectSortOrder :exec
UPDATE projects SET
  sort_order = $2,
  updated_by_email = $3,
  updated_by_display_name = $4,
  updated_at = now()
WHERE slug = $1
  AND deleted_at IS NULL
`

type UpdateProjectSortOrderParams struct {
	Slug                 string `json:"slug"`
	SortOrder            int32  `json:"sort_order"`
	UpdatedByEmail       string `json:"updated_by_email"`
	UpdatedByDisplayName string `json:"updated_by_display_name"`
}

func (q *Queries) UpdateProjectSortOrder(ctx context.Context, arg UpdateProjectSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateProjectSortOrder,
		arg.Slug,
		arg.SortOrder,
		arg.UpdatedByEmail,
		arg.UpdatedByDisplayName,
	)
	return err
}
