// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (user_email, user_display_name, action, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, user_email, user_display_name, action, payload, created_at
`

type InsertAuditLogParams struct {
	UserEmail       string `json:"user_email"`
	UserDisplayName string `json:"user_display_name"`
	Action          string `json:"action"`
	Payload         []byte `json:"payload"`
}

type InsertAuditLogRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserEmail       string             `json:"user_email"`
	UserDisplayName string             `json:"user_display_name"`
	Action          string             `json:"action"`
	Payload         []byte             `json:"payload"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (InsertAuditLogRow, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserEmail,
		arg.UserDisplayName,
		arg.Action,
		arg.Payload,
	)
	var i InsertAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.UserDisplayName,
		&i.Action,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
