// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID pgtype.UUID `json:"id"`
	// Authenticated admin email at the time of the action
	UserEmail string             `json:"user_email"`
	Action    string             `json:"action"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Authenticated admin display name at the time of the action
	UserDisplayName string `json:"user_display_name"`
}

type Project struct {
	ID           pgtype.UUID        `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Client       string             `json:"client"`
	Role         string             `json:"role"`
	Summary      string             `json:"summary"`
	Body         []byte             `json:"body"`
	ThumbnailUrl string             `json:"thumbnail_url"`
	SortOrder    int32              `json:"sort_order"`
	Status       string             `json:"status"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	// When set, project is soft-deleted (hidden from public + default admin lists; recoverable)
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	// Admin email that created the project
	CreatedByEmail string `json:"created_by_email"`
	// Admin display name that created the project
	CreatedByDisplayName string `json:"created_by_display_name"`
	// Admin email that last updated the project
	UpdatedByEmail string `json:"updated_by_email"`
	// Admin display name that last updated the project
	UpdatedByDisplayName string `json:"updated_by_display_name"`
}

type SiteSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
