// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublishedProjectBySlug = `-- name: GetPublishedProjectBySlug :one
SELECT
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
FROM projects
WHERE slug = $1
  AND status = 'published'
  AND deleted_at IS NULL
`

func (q *Queries) GetPublishedProjectBySlug(ctx context.Context, slug string) (Project, error) {
	row := q.db.QueryRow(ctx, getPublishedProjectBySlug, slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Client,
		&i.Role,
		&i.Summary,
		&i.Body,
		&i.ThumbnailUrl,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByEmail,
		&i.CreatedByDisplayName,
		&i.UpdatedByEmail,
		&i.UpdatedByDisplayName,
	)
	return i, err
}

const listPublishedProjects = `-- name: ListPublishedProjects :many
SELECT
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
FROM projects
WHERE status = 'published'
  AND deleted_at IS NULL
ORDER BY sort_order ASC
`

func (q *Queries) ListPublishedProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listPublishedProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Client,
			&i.Role,
			&i.Summary,
			&i.Body,
			&i.ThumbnailUrl,
			&i.SortOrder,
			&i.Status,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedByEmail,
			&i.CreatedByDisplayName,
			&i.UpdatedByEmail,
			&i.UpdatedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (slug) WHERE deleted_at IS NULL DO UPDATE SET
  title = EXCLUDED.title,
  client = EXCLUDED.client,
  role = EXCLUDED.role,
  summary = EXCLUDED.summary,
  body = EXCLUDED.body,
  thumbnail_url = EXCLUDED.thumbnail_url,
  sort_order = EXCLUDED.sort_order,
  status = EXCLUDED.status,
  published_at = EXCLUDED.published_at,
  updated_at = now()
RETURNING
  id,
  slug,
  title,
  client,
  role,
  summary,
  body,
  thumbnail_url,
  sort_order,
  status,
  published_at,
  created_at,
  updated_at,
  deleted_at,
  created_by_email,
  created_by_display_name,
  updated_by_email,
  updated_by_display_name
`

type UpsertProjectParams struct {
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Client       string             `json:"client"`
	Role         string             `json:"role"`
	Summary      string             `json:"summary"`
	Body         []byte             `json:"body"`
	ThumbnailUrl string             `json:"thumbnail_url"`
	SortOrder    int32              `json:"sort_order"`
	Status       string             `json:"status"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.Slug,
		arg.Title,
		arg.Client,
		arg.Role,
		arg.Summary,
		arg.Body,
		arg.ThumbnailUrl,
		arg.SortOrder,
		arg.Status,
		arg.PublishedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Client,
		&i.Role,
		&i.Summary,
		&i.Body,
		&i.ThumbnailUrl,
		&i.SortOrder,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByEmail,
		&i.CreatedByDisplayName,
		&i.UpdatedByEmail,
		&i.UpdatedByDisplayName,
	)
	return i, err
}
